### ISSUE TITLE
window下syscall.SIGTSTP找不到

### ISSUE THREAD

**Issue by hby07** [LockGit/gochat#14]
报错信息：
# gochat/api
api\chat.go:56:88: undefined: syscall.SIGTSTP
我查了一下，似乎是window中的go没有这个变量。有没有什么解决办法？在window中可以用哪个变量代替呢？

**Comment by LockGit** [comment]
方案1：快速解决，你可以在windows上把syscall.SIGTSTP这个移除
方案2：用提供的docker镜像启动

**Comment by hby07** [comment]
谢谢啦。我把这个注释掉了

**Comment by LockGit** [comment]
最新分支已经移除相关信号监控
