### ISSUE TITLE
能出Android iOS  SDK 吗？

### ISSUE THREAD

**Issue by zkbqhuang** [LockGit/gochat#15]
如题

**Comment by LockGit** [comment]
@zkbqhuang tcp消息投递与接收测试代码在本项目pkg/stickpackage目录中的:stickpackage_test.go文件中的Test_TcpClient方法
其中stickpackage.go文件主要为实现tcp拆包解包时用到，可以追踪下其中Pack与Unpack方法的调用地方，android,ios等其他对接语言需要完成对应的拆包解包
