### ISSUE TITLE
作者有没有出个文档的计划?

### ISSUE THREAD

**Issue by hby07** [LockGit/gochat#22]
关注这个项目有一段时间了,感觉如果有一份文档的话会很有用.
或者增加一些测试用例也不错.

**Comment by LockGit** [comment]
如果时间多确实可以出一个更详细的，不过我感觉readme应该也比较详细了，这个项目如果要完善还有很多地方

**Comment by hby07** [comment]
加油啊，有机会我也做点贡献😁
