### ISSUE TITLE
架构合理吗？

### ISSUE THREAD

**Issue by kekemuyu** [LockGit/gochat#25]
没有做过微服务架构，但我认为一个不大的程序分成这么多服务真的合理吗？各个服务之间有通讯成本，整个程序也增加了很多管理的成本。

**Comment by LockGit** [comment]
@kekemuyu 没有很多服务，核心只有3层。希望是如果要水平扩展，各层之间互不影响，松耦合，一般rpc通讯的成本不会成为瓶颈的
