### ISSUE TITLE
task 层 etcd 的疑惑 

### ISSUE THREAD

**Issue by BeanWei** [LockGit/gochat#26]
https://github.com/LockGit/gochat/blob/cdd3b0b5c2be68ce1df7d429be83805a2b3d762b/task/rpc.go#L23

https://github.com/LockGit/gochat/blob/cdd3b0b5c2be68ce1df7d429be83805a2b3d762b/task/rpc.go#L36

这里 etcd 并没起到作用吧，初始化时已经固定了服务地址，那 etcd 的作用是啥。

**Comment by LockGit** [comment]
@BeanWei 其实还需要有个优化，结合rpcx，就是watch etcd的中对应的kv变化，动态更新服务地址

**Comment by robin-hzc** [comment]
我也遇到这个问题了。 加了一个WatchServer去比较RpcConnectClientList的key。不然集群服务非同步上线下线会有问题

**Comment by 576498007** [comment]
@robin-hzc 能看看您WatchServer的代码么？我自己也有一些想法，就是定时轮询去查询，然后发现变动了就把缓存的client.XClient也进行变动，但是感觉差点意思。。谢谢您了。ruanmingchen@outlook.com

**Comment by 576498007** [comment]
@robin-hzc 能看看您WatchServer的代码么？我自己也有一些想法，就是定时轮询去查询，然后发现变动了就把缓存的client.XClient也进行变动，但是感觉差点意思。希望能得到您的帮助，谢谢您了。[ruanmingchen@outlook.com](mailto:ruanmingchen@outlook.com)

**Comment by robin-hzc** [comment]
@576498007 
func (task *Task) InitConnectRpcClient() (err error) {
	etcdConfig := config.Conf.Common.CommonEtcd
	d, err := etcdClient.NewEtcdV3Discovery(etcdConfig.BasePath, etcdConfig.ServerPathConnect, []string{etcdConfig.Host}, true, nil)
	if len(d.GetServices()) <= 0 {
		task.Logs.Panic("no etcd server find! err:", err.Error())
	}
	RpcConnectClientList = make(map[string]client.XClient, len(d.GetServices()))
	for _, connectConf := range d.GetServices() {
		//task.Logs.Infof("key is:%s,value is:%s", connectConf.Key, connectConf.Value)
		connectConf.Value = strings.Replace(connectConf.Value, "=&tps=0", "", 1)
		//strings.Split(connectConf.Value,&)
		//serverId, err := strconv.ParseInt(connectConf.Value, 10, 64)
		//serverId := connectConf.Value
		serverId, err := task.GetRealServerId(connectConf.Value)
		if err != nil {
			task.Logs.Panicf("InitConnect err，Can't find serverId. error: %s", err.Error())
		}

		cn, err := client.NewPeer2PeerDiscovery(connectConf.Key, "")
		if err != nil {
			task.Logs.Panicf("NewPeer2PeerDiscovery err, error: %s", err.Error())
		}
		//under serverId
		RpcConnectClientList[serverId] = client.NewXClient(etcdConfig.ServerPathConnect, client.Failtry, client.RandomSelect, cn, client.DefaultOption)
		task.Logs.Infof("InitConnectRpcClient addr %s, v %+v", connectConf.Key, RpcConnectClientList[serverId])
	}
	//监听服务
	go task.WatchServer(d)
	return
}

/*WatchServer
 *@Description: 服务监控
 *@receiver task
 *@param ws
 */
func (task *Task) WatchServer(c client.ServiceDiscovery) {
	for kv := range c.WatchService() {
		for _, v := range kv {
			//task.Logs.Info("v.Value:",v.Value)
			//v.Value = strings.Replace(v.Value, "=&tps=0", "", 1)
			serverId, err := task.GetRealServerId(v.Value)
			if err != nil {
				continue
			}
			if _, ok := RpcConnectClientList[serverId]; !ok {
				cn, err := client.NewPeer2PeerDiscovery(v.Key, "")
				if err != nil {
					task.Logs.Info("NewPeer2PeerDiscovery fail: ", err.Error())
					continue
				}
				RpcConnectClientList[serverId] = client.NewXClient(config.Conf.Common.CommonEtcd.ServerPathConnect, client.Failtry, client.RandomSelect, cn, client.DefaultOption)
				task.Logs.Infof("WatchService add key %s, v %+v", v.Key, RpcConnectClientList[serverId])
			}
		}
		if len(kv) != len(RpcConnectClientList) {
			kvMap := make(map[string]*client.KVPair)
			for _, v1 := range kv {
				//v1.Value = strings.Replace(v1.Value, "=&tps=0", "", 1)
				id, err := task.GetRealServerId(v1.Value)
				if err != nil {
					continue
				}
				kvMap[id] = v1
			}
			for k, _ := range RpcConnectClientList {
				if _, ok := kvMap[k]; !ok {
					delete(RpcConnectClientList, k)
					task.Logs.Infof("delete server Id: %s,rpc list: %v", k, RpcConnectClientList)
				}
			}
		}
	}
}

func (task *Task) GetRealServerId(str string) (string, error) {
	if str == "" {
		return "", nil
	}
	vStr := str[strings.LastIndex(str, "&")+1:]
	if strings.LastIndex(vStr, "=") > 0 {
		return vStr[0:strings.LastIndex(vStr, "=")], nil
	} else {
		return str, nil
	}
}

**Comment by robin-hzc** [comment]
@576498007 
`func (task *Task) InitConnectRpcClient() (err error) {
	etcdConfig := config.Conf.Common.CommonEtcd
	d, err := etcdClient.NewEtcdV3Discovery(etcdConfig.BasePath, etcdConfig.ServerPathConnect, []string{etcdConfig.Host}, true, nil)
	if len(d.GetServices()) <= 0 {
		task.Logs.Panic("no etcd server find! err:", err.Error())
	}
	RpcConnectClientList = make(map[string]client.XClient, len(d.GetServices()))
	for _, connectConf := range d.GetServices() {
		//task.Logs.Infof("key is:%s,value is:%s", connectConf.Key, connectConf.Value)
		connectConf.Value = strings.Replace(connectConf.Value, "=&tps=0", "", 1)
		//strings.Split(connectConf.Value,&)
		//serverId, err := strconv.ParseInt(connectConf.Value, 10, 64)
		//serverId := connectConf.Value
		serverId, err := task.GetRealServerId(connectConf.Value)
		if err != nil {
			task.Logs.Panicf("InitConnect err，Can't find serverId. error: %s", err.Error())
		}

		cn, err := client.NewPeer2PeerDiscovery(connectConf.Key, "")
		if err != nil {
			task.Logs.Panicf("NewPeer2PeerDiscovery err, error: %s", err.Error())
		}
		//under serverId
		RpcConnectClientList[serverId] = client.NewXClient(etcdConfig.ServerPathConnect, client.Failtry, client.RandomSelect, cn, client.DefaultOption)
		task.Logs.Infof("InitConnectRpcClient addr %s, v %+v", connectConf.Key, RpcConnectClientList[serverId])
	}
	//监听服务
	go task.WatchServer(d)
	return
}

/*WatchServer
 *@Description: 服务监控
 *@receiver task
 *@param ws
 */
func (task *Task) WatchServer(c client.ServiceDiscovery) {
	for kv := range c.WatchService() {
		for _, v := range kv {
			//task.Logs.Info("v.Value:",v.Value)
			//v.Value = strings.Replace(v.Value, "=&tps=0", "", 1)
			serverId, err := task.GetRealServerId(v.Value)
			if err != nil {
				continue
			}
			if _, ok := RpcConnectClientList[serverId]; !ok {
				cn, err := client.NewPeer2PeerDiscovery(v.Key, "")
				if err != nil {
					task.Logs.Info("NewPeer2PeerDiscovery fail: ", err.Error())
					continue
				}
				RpcConnectClientList[serverId] = client.NewXClient(config.Conf.Common.CommonEtcd.ServerPathConnect, client.Failtry, client.RandomSelect, cn, client.DefaultOption)
				task.Logs.Infof("WatchService add key %s, v %+v", v.Key, RpcConnectClientList[serverId])
			}
		}
		if len(kv) != len(RpcConnectClientList) {
			kvMap := make(map[string]*client.KVPair)
			for _, v1 := range kv {
				//v1.Value = strings.Replace(v1.Value, "=&tps=0", "", 1)
				id, err := task.GetRealServerId(v1.Value)
				if err != nil {
					continue
				}
				kvMap[id] = v1
			}
			for k, _ := range RpcConnectClientList {
				if _, ok := kvMap[k]; !ok {
					delete(RpcConnectClientList, k)
					task.Logs.Infof("delete server Id: %s,rpc list: %v", k, RpcConnectClientList)
				}
			}
		}
	}
}

func (task *Task) GetRealServerId(str string) (string, error) {
	if str == "" {
		return "", nil
	}
	vStr := str[strings.LastIndex(str, "&")+1:]
	if strings.LastIndex(vStr, "=") > 0 {
		return vStr[0:strings.LastIndex(vStr, "=")], nil
	} else {
		return str, nil
	}
}`

**Comment by robin-hzc** [comment]
@576498007 我用了一阵  暂时没发现什么问题。go mod 已经升级到1.17

**Comment by 576498007** [comment]
@robin-hzc **感谢大佬**

**Comment by LockGit** [comment]
以上问题优化已经更新到主分支
