### ISSUE TITLE
github.com/smallnest/rpcx 版本有问题

### ISSUE THREAD

**Issue by zdjniubi** [LockGit/gochat#29]
项目默认的rpcx版本是down不下来的，显示没有这个库
改成默认的版本：
![image](https://user-images.githubusercontent.com/39577077/127110910-677d4e77-a9bf-4af5-ad54-588636e77493.png)
？？？

**Comment by LockGit** [comment]
@zdjniubi vendor整个仓库都打包了在仓库里，按理说不需要再次download的了

**Comment by LockGit** [comment]
以上问题已经更新，请使用最新版本
