### ISSUE TITLE
发送消息接收不到

### ISSUE THREAD

**Issue by jerrylvq** [LockGit/gochat#32]
task 服务报错信息    **level=info msg="task queue block timeout,no msg err:redis: nil"**

谁帮忙解决下

**Comment by LockGit** [comment]
看看各个进程是不是running，提供尽可能多的信息，没有上下文让别人如何帮你

**Comment by jerrylvq** [comment]
D:\work\tfiir\go\src\gochat>gochat.bin -module task
start run task module
time="2021-09-29T14:23:59+08:00" level=info msg="key is:tcp@0.0.0.0:6914,value is:tcp-dda7380e-6dca-4a83-bd99-56d5070f40ff"
time="2021-09-29T14:23:59+08:00" level=info msg="InitConnectRpcClient addr tcp@0.0.0.0:6914, v &{failMode:2 selectMode:0 cachedClient:map[] breakers:{mu:{state:0 sema:0} read:{v:<nil>} dirty:map[] misses:0} servicePath:ConnectRpc option:{Group: Retries:3 TLSConfig:<nil> Block:<nil> RPCPath:/_rpcx_ ConnectTimeout:10000000000 ReadTimeout:0 WriteTimeout:0 BackupLatency:10000000 GenBreaker:<nil> SerializeType:3 CompressType:0 Heartbeat:false HeartbeatInterval:0} mu:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:0 readerWait:0} servers:map[tcp@0.0.0.0:6914:] discovery:0xc00030a220 selector:0xc000576210 isShutdown:false auth: Plugins:0xc000576228 ch:<nil> serverMessageChan:<nil>}"
time="2021-09-29T14:23:59+08:00" level=info msg="key is:tcp@0.0.0.0:6915,value is:tcp-dda7380e-6dca-4a83-bd99-56d5070f40ff"
time="2021-09-29T14:23:59+08:00" level=info msg="InitConnectRpcClient addr tcp@0.0.0.0:6915, v &{failMode:2 selectMode:0 cachedClient:map[] breakers:{mu:{state:0 sema:0} read:{v:<nil>} dirty:map[] misses:0} servicePath:ConnectRpc option:{Group: Retries:3 TLSConfig:<nil> Block:<nil> RPCPath:/_rpcx_ ConnectTimeout:10000000000 ReadTimeout:0 WriteTimeout:0 BackupLatency:10000000 GenBreaker:<nil> SerializeType:3 CompressType:0 Heartbeat:false HeartbeatInterval:0} mu:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:0 readerWait:0} servers:map[tcp@0.0.0.0:6915:] discovery:0xc000552000 selector:0xc00028a048 isShutdown:false auth: Plugins:0xc00028a0a8 ch:<nil> serverMessageChan:<nil>}"
run task module done!
time="2021-09-29T14:24:09+08:00" level=info msg="task queue block timeout,no msg err:redis: nil"

**Comment by LockGit** [comment]
@jerrylvq 这种不影响吧，10s超时没有取到数据打了个日志而已

**Comment by jerrylvq** [comment]
@LockGit 有别的联系方式么  麻烦帮忙看看

**Comment by jerrylvq** [comment]
发送消息后api服务正常：
time="2021-09-29T15:29:17+08:00" level=info msg="push msg info &{3  1 0 [123 34 99 111 100 101 34 58 48 44 34 109 115 103 34 58 34 49 50 51 34 44 34 102 114 111 109 85 115 101 114 73 100 34 58 51 44 34 102 114 111 109 85 115 101 114 78 97 109 101 34 58 34 100 101 109 111 34 44 34 116 111 85 115 101 114 73 100 34 58 48 44 34 116 111 85 115 101 114 78 97 109 101 34 58 34 34 44 34 114 111 111 109 73 100 34 58 49 44 34 111 112 34 58 51 44 34 99 114 101 97 116 101 84 105 109 101 34 58 34 50 48 50 49 45 48 57 45 50 57 32 49 53 58 50 57 58 49 55 34 125] 0 map[]}"
time="2021-09-29T15:29:17+08:00" level=info msg="broadcastRoomToConnect rpc  &{2 0 map[tcp@0.0.0.0:6915:0xc00029f1e0] {{0 0} {<nil>} map[] 0} ConnectRpc { 3 <nil> <nil> /_rpcx_ 10000000000 0 0 10000000 <nil> 3 0 false 0} {{0 0} 0 0 0 0} map[tcp@0.0.0.0:6915:] 0xc000552000 0xc00028a048 false  0xc00028a0a8 <nil> <nil>}"

**Comment by jerrylvq** [comment]
发送消息后api服务正常：

**Comment by jerrylvq** [comment]
发送消息后，api服务正常GIN] 2021/09/29 - 15:29:17 | 200 |      1.6972ms |       127.0.0.1 | POST     "/push/pushRoom"                   connect_tcp服务正常time="2021-09-29T15:29:17+08:00" level=info msg="PushRoomMsg msg &{RoomId:1 Msg:{Ver:1 Operation:3 SeqId:1443115648417796096 Body:[123 34 99 111 100 101 34 58 48 44 34 109 115 103 34 58 34 49 50 51 34 44 34 102 114 111 109 85 115 101 114 73 100 34 58 51 44 34 102 114 111 109 85 115 101 114 78 97 109 101 34 58 34 100 101 109 111 34 44 34 116 111 85 115 101 114 73 100 34 58 48 44 34 116 111 85 115 101 114 78 97 109 101 34 58 34 34 44 34 114 111 111 109 73 100 34 58 49 44 34 111 112 34 58 51 44 34 99 114 101 97 116 101 84 105 109 101 34 58 34 50 48 50 49 45 48 57 45 50 57 32 49 53 58 50 57 58 49 55 34 125]}}"                         task服务不正常： time="2021-09-29T15:29:17+08:00" level=info msg="push msg info &{3  1 0 [123 34 99 111 100 101 34 58 48 44 34 109 115 103 34 58 34 49 50 51 34 44 34 102 114 111 109 85 115 101 114 73 100 34 58 51 44 34 102 114 111 109 85 115 101 114 78 97 109 101 34 58 34 100 101 109 111 34 44 34 116 111 85 115 101 114 73 100 34 58 48 44 34 116 111 85 115 101 114 78 97 109 101 34 58 34 34 44 34 114 111 111 109 73 100 34 58 49 44 34 111 112 34 58 51 44 34 99 114 101 97 116 101 84 105 109 101 34 58 34 50 48 50 49 45 48 57 45 50 57 32 49 53 58 50 57 58 49 55 34 125] 0 map[]}"
time="2021-09-29T15:29:17+08:00" level=info msg="broadcastRoomToConnect rpc  &{2 0 map[tcp@0.0.0.0:6915:0xc00029f1e0] {{0 0} {<nil>} map[] 0} ConnectRpc { 3 <nil> <nil> /_rpcx_ 10000000000 0 0 10000000 <nil> 3 0 false 0} {{0 0} 0 0 0 0} map[tcp@0.0.0.0:6915:] 0xc000552000 0xc00028a048 false  0xc00028a0a8 <nil> <nil>}"

**Comment by jerrylvq** [comment]
问题是默认没支持tcp  得用websocket
