### ISSUE TITLE
Ubuntu部署gochat，win10浏览器访问失败

### ISSUE THREAD

**Issue by jiuyuan-light** [LockGit/gochat#39]
![image](https://user-images.githubusercontent.com/89025318/185727635-55fcc4db-ca7d-4d8a-8395-c3b4f9ccf264.png)
![image](https://user-images.githubusercontent.com/89025318/185727672-76f2b413-c315-4a03-ae94-41760b99101b.png)

**Comment by LockGit** [comment]
@jiuyuan-light 是本地部署还是部署在了个人vps上？
1，docker exec -it gochat-dev bash
2，supervisorctl status 看下各个进程状态

**Comment by jiuyuan-light** [comment]
> @jiuyuan-light是本地部署在个人vps上？ 1，docker exec -it gochat-dev bash 2，看部署supervisorctl status 看下部署或者进程状态

1，是本地部署，Ubuntu是win10中的一个vmware虚拟机，通过./gochat -module xxx命令启动的，无法使用supervisorctl status看进程状态。
2，进程应该没有问题，在Ubuntu中的浏览器可以正常注册和登陆。在win10和Ubuntu中抓包对比了下，Ubuntu中能捕获到截图中框起来的报文，win10中缺少。
![image](https://user-images.githubusercontent.com/89025318/185737154-648a665c-9c1c-460f-b0cc-430d39b394be.png)

**Comment by LockGit** [comment]
> > @jiuyuan-light是本地部署在个人vps上？ 1，docker exec -it gochat-dev bash 2，看部署supervisorctl status 看下部署或者进程状态
> 
> 1，是本地部署，Ubuntu是win10中的一个vmware虚拟机，通过./gochat -module xxx命令启动的，无法使用supervisorctl status看进程状态。 2，进程应该没有问题，在Ubuntu中的浏览器可以正常注册和登陆。在win10和Ubuntu中抓包对比了下，Ubuntu中能捕获到截图中框起来的报文，win10中缺少。 ![image](https://user-images.githubusercontent.com/89025318/185737154-648a665c-9c1c-460f-b0cc-430d39b394be.png)

其实用docker启动更方便。。

另外你在Ubuntu里启动，从windows宿主机访问，如果是nat模式，网络是不通的，前端页面请求的api和建立长链接是写死的127.0.0.1下的端口，这个在你windows宿主机访问估计是不可以的。

你可以看下reload.sh里的文件描述：
addr_http=${HOST_IP}:7070
addr_ws=${HOST_IP}:7000

sed -r -i "s/\/\/(\b[0-9]{1,3}\.){3}[0-9]{1,3}\b:[0-9]+/\/\/${addr_http}/g" site/static/js/main.5216e7a9.js
sed -r -i "s/\/\/(\b[0-9]{1,3}\.){3}[0-9]{1,3}\b:[0-9]+\/ws/\/\/${addr_ws}\/ws/g" site/static/js/main.5216e7a9.js
这个就是替换前端页面的api和websockets 的ip地址。。

如果你想要当前模式走通，至少要修改 这个地址为你虚拟机里的ip地址，且确保网络是通的。

**Comment by jiuyuan-light** [comment]
> > > @jiuyuan-light是本地部署在个人vps上？ 1，docker exec -it gochat-dev bash 2，看部署supervisorctl status 看下部署或者进程状态
> > 
> > 
> > 1，是本地部署，Ubuntu是win10中的一个vmware虚拟机，通过./gochat -module xxx命令启动的，无法使用supervisorctl status看进程状态。 2，进程应该没有问题，在Ubuntu中的浏览器可以正常注册和登陆。在win10和Ubuntu中抓包对比了下，Ubuntu中能捕获到截图中框起来的报文，win10中缺少。 ![image](https://user-images.githubusercontent.com/89025318/185737154-648a665c-9c1c-460f-b0cc-430d39b394be.png)
> 
> 其实用docker启动更方便。。
> 
> 另外你在Ubuntu里启动，从windows宿主机访问，如果是nat模式，网络是不通的，前端页面请求的api和建立长链接是写死的127.0.0.1下的端口，这个在你windows宿主机访问估计是不可以的。
> 
> 你可以看下reload.sh里的文件描述： addr_http=${HOST_IP}:7070 addr_ws=${HOST_IP}:7000
> 
> sed -r -i "s///(\b[0-9]{1,3}.){3}[0-9]{1,3}\b:[0-9]+///${addr_http}/g" site/static/js/main.5216e7a9.js sed -r -i "s///(\b[0-9]{1,3}.){3}[0-9]{1,3}\b:[0-9]+/ws///${addr_ws}/ws/g" site/static/js/main.5216e7a9.js 这个就是替换前端页面的api和websockets 的ip地址。。
> 
> 如果你想要当前模式走通，至少要修改 这个地址为你虚拟机里的ip地址，且确保网络是通的。

多谢帮助，问题已解决。改了main.5216e7a9.js中的ip地址后，win10可以正常注册和登陆了。
另外，我的win10和Ubuntu是only-host连接的，在同一网段，网络是通的。如果是nat连接的话，开端口映射就能访问Ubuntu了。
