### ISSUE TITLE
bucket会崩溃

### ISSUE THREAD

**Issue by robin-hzc** [LockGit/gochat#45]
fatal error: concurrent map read and map write

是不是因为60行的room返回的是指针所以仍然会触发b.rooms读写并发。

**Comment by LockGit** [comment]
应该不是，得看看详细的错误

**Comment by robin-hzc** [comment]
<img width="667" alt="WeChate7a290fc7e72768b2a61880dcd63dc97" src="https://user-images.githubusercontent.com/26951037/211749504-b76e9b68-a39f-46a8-a413-69c378475eb2.png">

**Comment by robin-hzc** [comment]
我对原来的websocket做了一些改动。加入了 socket 接收消息。
