### ISSUE TITLE
windows10下docker启动后打不开聊天界面

### ISSUE THREAD

**Issue by sunhaotian0122** [LockGit/gochat#46]
按照教程下载docker镜像启动后还是无法打开聊天界面，以下是运行截图，想问下问题大概出在哪啊？

![image](https://user-images.githubusercontent.com/19524078/218790633-fa45d4d3-497f-41fd-9ec5-661c60ac1915.png)

![image](https://user-images.githubusercontent.com/19524078/218791114-5ab18e92-8b21-458b-ba55-0aad0d4175bb.png)

**Comment by LockGit** [comment]
> 按照教程下载docker镜像启动后还是无法打开聊天界面，以下是运行截图，想问下问题大概出在哪啊？
> 
> ![image](https://user-images.githubusercontent.com/19524078/218790633-fa45d4d3-497f-41fd-9ec5-661c60ac1915.png)
> 
> ![image](https://user-images.githubusercontent.com/19524078/218791114-5ab18e92-8b21-458b-ba55-0aad0d4175bb.png)

登录进容器，supervisorctl status 看下各个进程的状态

**Comment by LockGit** [comment]
登录进容器，supervisorctl status 看下各个进程的状态 @sunhaotian0122

**Comment by LockGit** [comment]
要么把容器删除掉重新执行sh run.sh dev 127.0.0.1 ， 截图中第一步也报错了，但似乎是windows下docker的问题

**Comment by sunhaotian0122** [comment]
好像是那些映射的文件没有进去，你看是这样吗？
![image](https://user-images.githubusercontent.com/19524078/219019669-839041a6-b877-417c-8e57-73ebd4d42498.png)

**Comment by sunhaotian0122** [comment]
我现在把docker容器里面的文件都映射好了，但是reload.sh运行又出问题了，请问确定是1.18吗？好像还有个latest的
![image](https://user-images.githubusercontent.com/19524078/219028202-e19b77b8-c9c0-4c25-8b91-7210b3ac55a5.png)

**Comment by sunhaotian0122** [comment]
虽然不清楚为啥reload.sh脚本运行不了，不过我直接在容器里面运行脚本里的命令是可以的，现在我已经配置好了。
还有个问题想提醒下，Edge浏览器里面看不到注册和登陆的按钮，Chrome可以。
