### ISSUE TITLE
能把vender目录移除吗, clone 总是中断

### ISSUE THREAD

**Issue by lazyou** [LockGit/gochat#5]
vender 可以通过走代理自行下载.

**Comment by LockGit** [comment]
vendor 包含了相关依赖，整个项目文件只有10m左右，clone 中断是因为网络原因，你也可以直接下载zip包： wget https://github.com/LockGit/gochat/archive/master.zip

**Comment by LockGit** [comment]
通过走代理自行下载也是需要时间还要翻墙，不如clone下去的好，省的麻烦
