### ISSUE TITLE
connect设计有问题

### ISSUE THREAD

**Issue by linguanyuanA** [LockGit/gochat#57]
1. push 进去 select 如果sender满，消息是不是丢失了
2. 如果链接关闭，是否要对sender channel进行关闭？ 如果关闭了，是不是很多环节都不可靠了？

**Comment by LockGit** [comment]
> 1. push 进去 select 如果sender满，消息是不是丢失了
> 2. 如果链接关闭，是否要对sender channel进行关闭？ 如果关闭了，是不是很多环节都不可靠了？

有具体代码说明么

**Comment by shakeyo** [comment]
> 1. push 进去 select 如果sender满，消息是不是丢失了
> 2. 如果链接关闭，是否要对sender channel进行关闭？ 如果关闭了，是不是很多环节都不可靠了？

如果要保证可靠性，应该是增加ack机制，connect这么设计是没问题的
无论你怎么做，都有可能在链路中丢失消息，要保证上下行消息的可靠性，只能互相ack，就像tcp一样
