### ISSUE TITLE
开发环境问题

### ISSUE THREAD

**Issue by 1379** [LockGit/gochat#7]
有一个问题：
我clone下代码后，运行 go build ，告诉我需要编译go-sqlite3，并且需要gcc，于是我安装了gcc，之后又报错，提示我不能兼容64位，总之就是很多问题。请问作者的开发环境也是Windows吗？还是Linux?

**Comment by LockGit** [comment]
Mac OS ,  如果你一定要在windos上使用，那么就安装相关错误提示的依赖。另外建议使用docker构建 。

**Comment by cygamelife** [comment]
我用的腾讯云拉的docker启动，监听的8080没错，但是只能本地访问，不能跨机器啊，请问怎么配置接受远程连接

**Comment by LockGit** [comment]
@cygamelife 你有公网ip就可以远程访问，文档中有写：
如果你要部署在个人vps上,记得修改site/js/common.js中socketUrl与apiUrl的地址为你的vps的ip地址,并确保vps上没有针对相关端口的防火墙限制。

**Comment by cygamelife** [comment]
tcp6       0      0 :::8080                 :::*                    LISTEN      22458/docker-proxy  

已经修改过site/js/common.js中socketUrl与apiUrl的地址 为外网地址了，防火墙也试过没问题的，因为用别的tcp监听8080端口是可以访问的。不知道是不是因为用docker启动用的是tcp6的原因

**Comment by LockGit** [comment]
7000是websocket通讯端口，需要开
7070是api端口，需要开
