### ISSUE TITLE
无法找到quic-conn Repository

### ISSUE THREAD

**Issue by changeworld1** [LockGit/gochat#9]
fatal: repository 'https://github.com/rpcx-ecosystem/quic-conn/' not found

**Comment by LockGit** [comment]
使用docker构建试试，另外所依赖的包都一起提交到仓库了

**Comment by changeworld1** [comment]
好的，我在docker构建然后看下是否存在对应的依赖包，毕竟要进行二次开发 Thanks

**Comment by changeworld1** [comment]
docker 构建可以
